using System;
using System.Collections.Generic;
using System.Text;
using Everboot.Configuration;
using Microsoft.Extensions.Options;

namespace Everboot.Services;

/// <summary>
/// Renders the iPXE menu served at /boot.ipxe.
///
/// Structure:
///   :start                     main menu - one item per ISO + tools
///     -> goto :{slug}          per-ISO method submenu
///        :{slug}                method submenu (auto / direct / wimboot /
///                               sanhttp / saniscsi / memdisk / shell / back)
///          -> goto :{slug}-X   method body that actually boots
///
/// On any method failure: <c>goto methodfail</c> -> <c>goto $last-method-menu</c>,
/// which returns to the method submenu of the ISO the user was trying to
/// boot - not the main menu - so they can try a different method right away.
///
/// Windows 9x and "not-for-PXE" images (Ventoy) skip the submenu and just
/// show a notice + return to the main menu.
/// </summary>
internal sealed class BootConfigGenerator
{
    private readonly BootCatalog _catalog;
    private readonly EverbootOptions _options;

    public BootConfigGenerator(BootCatalog catalog, IOptions<EverbootOptions> options)
    {
        _catalog = catalog;
        _options = options.Value;
    }

    public string GenerateIpxeMenu(string serverAuthority)
    {
        var entries = _catalog.Entries;
        var sb = new StringBuilder(8192);

        sb.AppendLine("#!ipxe");
        sb.AppendLine("# Generated by Everboot");
        sb.AppendLine();

        EmitConsoleSetup(sb, serverAuthority);
        EmitMainMenu(sb, entries);
        EmitCommonLabels(sb);

        foreach (var entry in entries)
        {
            sb.AppendLine();
            if (entry.Metadata.WindowsEra == WindowsBootEra.NinexClass)
            {
                EmitWin9xEntry(sb, entry);
            }
            else if (entry.Metadata.Profile?.Family == DistroFamily.NotForPxe)
            {
                EmitNotForPxeEntry(sb, entry);
            }
            else
            {
                EmitMethodSubmenu(sb, entry);
                EmitMethodBodies(sb, serverAuthority, entry);
            }
        }

        return sb.ToString();
    }

    // -----------------------------------------------------------------
    // Console setup - resolution + optional background image. Both wrapped
    // in `|| echo` so a stock iPXE that doesn't support them keeps going
    // rather than aborting the whole script.
    // -----------------------------------------------------------------

    private void EmitConsoleSetup(StringBuilder sb, string authority)
    {
        var emitted = false;
        if (TryParseResolution(_options.Menu.ConsoleResolution, out var width, out var height))
        {
            sb.AppendLine($"console --x {width} --y {height} || echo (console {width}x{height} unsupported - keeping default mode)");
            emitted = true;
        }
        if (!string.IsNullOrWhiteSpace(_options.Menu.BackgroundImage))
        {
            var encoded = Uri.EscapeDataString(_options.Menu.BackgroundImage.Trim());
            sb.AppendLine($"console --picture http://{authority}/files/{encoded} || echo (background image unsupported - needs CONSOLE_PCX-built iPXE)");
            emitted = true;
        }
        if (emitted)
        {
            sb.AppendLine();
        }
    }

    private static bool TryParseResolution(string? input, out int width, out int height)
    {
        width = 0;
        height = 0;
        if (string.IsNullOrWhiteSpace(input))
        {
            return false;
        }
        var parts = input.Trim().Split('x', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        if (parts.Length != 2)
        {
            return false;
        }
        if (!int.TryParse(parts[0], out width) || !int.TryParse(parts[1], out height))
        {
            return false;
        }
        return width >= 320 && height >= 200 && width <= 7680 && height <= 4320;
    }

    // -----------------------------------------------------------------
    // Main menu (the top-level list of ISOs + tool items)
    // -----------------------------------------------------------------

    private void EmitMainMenu(StringBuilder sb, IReadOnlyList<IsoEntry> entries)
    {
        sb.AppendLine(":start");
        sb.AppendLine($"menu {_options.Menu.Title}");
        sb.AppendLine("item --gap -- ----------- Boot images -----------");

        if (entries.Count == 0)
        {
            sb.AppendLine("item --gap -- (no images found - drop *.iso or *.img into data/isos/)");
        }
        else
        {
            for (var i = 0; i < entries.Count; i++)
            {
                var entry = entries[i];
                // Numeric hotkeys for the first nine entries (1-9). Beyond
                // that, items still appear and are reachable via arrow keys.
                var keyArg = i < 9 ? $"--key {i + 1} " : string.Empty;
                sb.AppendLine($"item {keyArg}{entry.Slug} {entry.DisplayName}  [{FormatSize(entry.SizeBytes)}]{LabelTag(entry)}");
            }
        }

        sb.AppendLine("item --gap -- ------------ Tools -----------------");
        sb.AppendLine("item --key s shell  iPXE shell");
        sb.AppendLine("item --key r reboot Reboot");
        sb.AppendLine("item --key x exit   Exit iPXE (continue local boot)");

        var defaultItem = entries.Count > 0 ? entries[0].Slug : "exit";
        var timeoutMs = Math.Max(0, _options.Menu.TimeoutSeconds) * 1000;
        sb.AppendLine($"choose --default {defaultItem} --timeout {timeoutMs} target && goto ${{target}} || goto cancel");
    }

    // -----------------------------------------------------------------
    // Common labels reachable from any menu / method body
    // -----------------------------------------------------------------

    private static void EmitCommonLabels(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine(":cancel");
        sb.AppendLine("echo Menu cancelled, exiting iPXE.");
        sb.AppendLine("exit");

        sb.AppendLine();
        sb.AppendLine(":methodfail");
        sb.AppendLine("echo Boot method failed. Returning to method menu in 5s. (Ctrl+B for iPXE shell)");
        sb.AppendLine("sleep 5");
        sb.AppendLine("isset ${last-method-menu} && goto ${last-method-menu} || goto start");

        sb.AppendLine();
        sb.AppendLine(":shell");
        sb.AppendLine("echo Type 'exit' to return to the menu.");
        sb.AppendLine("shell");
        sb.AppendLine("goto start");

        sb.AppendLine();
        sb.AppendLine(":reboot");
        sb.AppendLine("reboot");

        sb.AppendLine();
        sb.AppendLine(":exit");
        sb.AppendLine("exit");
    }

    // -----------------------------------------------------------------
    // Per-ISO method submenu - the new "give them every option" UI.
    // -----------------------------------------------------------------

    private void EmitMethodSubmenu(StringBuilder sb, IsoEntry entry)
    {
        var slug = entry.Slug;
        var hasDirect = HasDirectBoot(entry);
        var isWin = entry.Metadata.IsModernWindows;
        var iscsiOn = _options.Iscsi.Enabled;

        sb.AppendLine($":{slug}");
        sb.AppendLine($"set last-method-menu {slug}");

        if (entry.Metadata.WindowsEra == WindowsBootEra.XpClass)
        {
            sb.AppendLine("echo NOTE: Windows XP-era PXE is unreliable on every method; expect to experiment.");
        }
        if (entry.Metadata.Profile?.Caveat is { } caveat)
        {
            sb.AppendLine($"echo NOTE: {Sanitize(caveat)}");
        }

        sb.AppendLine($"menu {entry.DisplayName} - choose a boot method");
        sb.AppendLine("item --gap -- ------------ Boot methods ------------");
        sb.AppendLine($"item --key a {slug}-auto      Auto (recommended)");

        if (hasDirect)
        {
            var p = entry.Metadata.Profile!.DisplayName;
            sb.AppendLine($"item --key d {slug}-direct    Direct kernel boot ({p})");
        }
        if (isWin)
        {
            sb.AppendLine($"item --key w {slug}-wimboot   wimboot (load Windows PE)");
        }

        sb.AppendLine($"item --key h {slug}-sanhttp   sanboot via HTTP (virtual CD)");
        if (iscsiOn)
        {
            sb.AppendLine($"item --key i {slug}-saniscsi  sanboot via iSCSI (more reliable for Windows-class boot)");
        }
        sb.AppendLine($"item --key m {slug}-memdisk   memdisk (load entire image into RAM)");
        sb.AppendLine($"item --key s {slug}-shell     Drop to iPXE shell (variables preset)");

        sb.AppendLine("item --gap -- ------------ Navigation ------------");
        sb.AppendLine("item --key b start            <-- Back to main menu");

        var methodTimeoutMs = Math.Max(0, _options.Menu.MethodMenuTimeoutSeconds) * 1000;
        sb.AppendLine($"choose --default {slug}-auto --timeout {methodTimeoutMs} method && goto ${{method}} || goto start");
    }

    // -----------------------------------------------------------------
    // Method bodies - the actual boot logic for each chosen method.
    // -----------------------------------------------------------------

    private void EmitMethodBodies(StringBuilder sb, string authority, IsoEntry entry)
    {
        var slug = entry.Slug;
        var hasDirect = HasDirectBoot(entry);
        var isWin = entry.Metadata.IsModernWindows;
        var iscsiOn = _options.Iscsi.Enabled;

        // Auto: route to whichever specific method our detection prefers.
        sb.AppendLine();
        sb.AppendLine($":{slug}-auto");
        sb.AppendLine($"set last-method-menu {slug}");
        if (isWin)
        {
            sb.AppendLine($"echo Auto: wimboot (modern Windows detected)");
            sb.AppendLine($"goto {slug}-wimboot");
        }
        else if (hasDirect)
        {
            sb.AppendLine($"echo Auto: direct kernel boot ({entry.Metadata.Profile!.DisplayName} profile)");
            sb.AppendLine($"goto {slug}-direct");
        }
        else if (entry.IsLikelyFloppy)
        {
            sb.AppendLine($"echo Auto: memdisk (looks like a floppy image)");
            sb.AppendLine($"goto {slug}-memdisk");
        }
        else
        {
            sb.AppendLine($"echo Auto: sanboot via HTTP");
            sb.AppendLine($"goto {slug}-sanhttp");
        }

        if (hasDirect)
        {
            sb.AppendLine();
            sb.AppendLine($":{slug}-direct");
            sb.AppendLine($"set last-method-menu {slug}");
            EmitDirectKernelBody(sb, authority, entry);
        }

        if (isWin)
        {
            sb.AppendLine();
            sb.AppendLine($":{slug}-wimboot");
            sb.AppendLine($"set last-method-menu {slug}");
            EmitWimbootChain(sb, authority, slug, entry.Metadata.WindowsFiles!);
        }

        // sanboot via HTTP - always available
        sb.AppendLine();
        sb.AppendLine($":{slug}-sanhttp");
        sb.AppendLine($"set last-method-menu {slug}");
        sb.AppendLine($"echo sanboot via HTTP: {entry.FileName}");
        sb.AppendLine($"set iso-url http://{authority}/isos/{Uri.EscapeDataString(entry.FileName)}");
        sb.AppendLine("sanboot --no-describe ${iso-url} || goto methodfail");

        if (iscsiOn)
        {
            sb.AppendLine();
            sb.AppendLine($":{slug}-saniscsi");
            sb.AppendLine($"set last-method-menu {slug}");
            var host = authority.Split(':')[0];
            var iqn = $"{_options.Iscsi.IqnBase}:iso-{slug}";
            sb.AppendLine($"echo sanboot via iSCSI: {iqn}");
            sb.AppendLine($"sanboot --no-describe iscsi:{host}::::{iqn} || goto methodfail");
        }

        // memdisk - always available
        sb.AppendLine();
        sb.AppendLine($":{slug}-memdisk");
        sb.AppendLine($"set last-method-menu {slug}");
        sb.AppendLine($"echo memdisk: loading {entry.FileName} ({FormatSize(entry.SizeBytes)}) into RAM");
        sb.AppendLine($"kernel http://{authority}/files/memdisk iso raw || goto methodfail");
        sb.AppendLine($"initrd http://{authority}/isos/{Uri.EscapeDataString(entry.FileName)} || goto methodfail");
        sb.AppendLine("boot || goto methodfail");

        // shell with helpful variables preset
        sb.AppendLine();
        sb.AppendLine($":{slug}-shell");
        sb.AppendLine($"set last-method-menu {slug}");
        sb.AppendLine($"set iso-url http://{authority}/isos/{Uri.EscapeDataString(entry.FileName)}");
        sb.AppendLine($"set iso-base http://{authority}/iso/{slug}");
        sb.AppendLine($"set memdisk-url http://{authority}/files/memdisk");
        sb.AppendLine($"echo Variables set for {entry.FileName}:");
        sb.AppendLine($"echo   iso-url     = $" + "{iso-url}");
        sb.AppendLine($"echo   iso-base    = $" + "{iso-base}  (browse files inside the ISO)");
        sb.AppendLine($"echo   memdisk-url = $" + "{memdisk-url}");
        sb.AppendLine($"echo");
        sb.AppendLine($"echo Try:  sanboot $" + "{iso-url}");
        sb.AppendLine($"echo Or:   kernel $" + "{iso-base}/path/to/vmlinuz <args>  ; initrd $" + "{iso-base}/path/to/initrd ; boot");
        sb.AppendLine($"echo Exit shell with 'exit' to return to method menu.");
        sb.AppendLine($"shell");
        sb.AppendLine($"goto {slug}");
    }

    private static void EmitDirectKernelBody(StringBuilder sb, string authority, IsoEntry entry)
    {
        var profile = entry.Metadata.Profile!;
        var direct = profile.DirectBoot!;

        var args = direct.KernelArgs
            .Replace("{server}", authority, StringComparison.Ordinal)
            .Replace("{slug}", entry.Slug, StringComparison.Ordinal)
            .Replace("{file}", Uri.EscapeDataString(entry.FileName), StringComparison.Ordinal);

        sb.AppendLine($"echo Direct kernel boot via {profile.DisplayName} profile");
        sb.AppendLine($"kernel http://{authority}/iso/{entry.Slug}/{EncodePath(direct.KernelPath)} {args} || goto methodfail");
        sb.AppendLine($"initrd http://{authority}/iso/{entry.Slug}/{EncodePath(direct.InitrdPath)} || goto methodfail");
        sb.AppendLine("boot || goto methodfail");
    }

    private static void EmitWimbootChain(StringBuilder sb, string authority, string slug, WindowsBootFiles wf)
    {
        if (wf.HasBiosChain && wf.HasEfiChain)
        {
            sb.AppendLine($"iseq $" + "{platform} efi && goto " + $"{slug}-wimboot-efi || goto {slug}-wimboot-bios");
            sb.AppendLine();
            sb.AppendLine($":{slug}-wimboot-bios");
            sb.AppendLine($"set last-method-menu {slug}");
            EmitBiosChain(sb, authority, slug, wf);
            sb.AppendLine();
            sb.AppendLine($":{slug}-wimboot-efi");
            sb.AppendLine($"set last-method-menu {slug}");
            EmitEfiChain(sb, authority, slug, wf);
            return;
        }

        if (wf.HasBiosChain)
        {
            EmitBiosChain(sb, authority, slug, wf);
        }
        else
        {
            EmitEfiChain(sb, authority, slug, wf);
        }
    }

    private static void EmitBiosChain(StringBuilder sb, string authority, string slug, WindowsBootFiles wf)
    {
        sb.AppendLine($"set base http://{authority}/iso/{slug}");
        sb.AppendLine($"set wimboot-url http://{authority}/files/wimboot");
        sb.AppendLine("kernel ${wimboot-url} || goto methodfail");
        sb.AppendLine($"initrd --name bootmgr     ${{base}}/{EncodePath(wf.Bootmgr!)}     bootmgr");
        sb.AppendLine($"initrd --name BCD         ${{base}}/{EncodePath(wf.Bcd!)}         BCD");
        sb.AppendLine($"initrd --name boot.sdi    ${{base}}/{EncodePath(wf.BootSdi!)}    boot.sdi");
        sb.AppendLine($"initrd --name boot.wim    ${{base}}/{EncodePath(wf.BootWim)}    boot.wim");
        sb.AppendLine("boot || goto methodfail");
    }

    private static void EmitEfiChain(StringBuilder sb, string authority, string slug, WindowsBootFiles wf)
    {
        sb.AppendLine($"set base http://{authority}/iso/{slug}");
        sb.AppendLine($"set wimboot-url http://{authority}/files/wimboot");
        sb.AppendLine("kernel ${wimboot-url} || goto methodfail");
        sb.AppendLine($"initrd --name BCD         ${{base}}/{EncodePath(wf.BcdEfi!)}     BCD");
        if (wf.BootmgrEfi is not null)
        {
            sb.AppendLine($"initrd --name bootmgfw.efi ${{base}}/{EncodePath(wf.BootmgrEfi)} bootmgfw.efi");
        }
        sb.AppendLine($"initrd --name boot.wim    ${{base}}/{EncodePath(wf.BootWim)}    boot.wim");
        sb.AppendLine("boot || goto methodfail");
    }

    private static void EmitWin9xEntry(StringBuilder sb, IsoEntry entry)
    {
        sb.AppendLine($":{entry.Slug}");
        sb.AppendLine($"echo {entry.DisplayName}: Windows 9x install media cannot boot directly via PXE.");
        sb.AppendLine("echo To install: PXE-boot FreeDOS via 'kernel memdisk' + a DOS floppy image,");
        sb.AppendLine("echo then run setup.exe from a mounted network share.");
        sb.AppendLine("echo Returning to menu in 8 seconds.");
        sb.AppendLine("sleep 8");
        sb.AppendLine("goto start");
    }

    private static void EmitNotForPxeEntry(StringBuilder sb, IsoEntry entry)
    {
        var profile = entry.Metadata.Profile!;
        sb.AppendLine($":{entry.Slug}");
        sb.AppendLine($"echo {profile.DisplayName} is not a PXE boot target.");
        if (profile.Caveat is not null)
        {
            sb.AppendLine($"echo {Sanitize(profile.Caveat)}");
        }
        sb.AppendLine("echo Returning to menu in 5 seconds.");
        sb.AppendLine("sleep 5");
        sb.AppendLine("goto start");
    }

    // -----------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------

    private static bool HasDirectBoot(IsoEntry entry) =>
        entry.Metadata.Profile?.DirectBoot is not null && !entry.Metadata.IsModernWindows;

    private static string LabelTag(IsoEntry entry)
    {
        if (entry.Metadata.Profile?.Caveat is { } caveat)
        {
            return $"  ({entry.Metadata.Profile.DisplayName} - {caveat})";
        }

        return entry.Metadata.WindowsEra switch
        {
            WindowsBootEra.Modern => entry.Metadata.Profile is { } mp
                ? $"  ({mp.DisplayName} - Windows)"
                : "  (Windows)",
            WindowsBootEra.XpClass => "  (Windows XP-era - PXE may fail)",
            WindowsBootEra.NinexClass => "  (Windows 9x - not PXE-bootable)",
            _ => entry.IsLikelyFloppy
                ? "  (floppy)"
                : entry.Metadata.Profile is { } p
                    ? FamilyLabel(p)
                    : string.Empty,
        };
    }

    private static string FamilyLabel(DistroProfile p) => p.Family switch
    {
        DistroFamily.LinuxLive => $"  ({p.DisplayName} - Linux Live)",
        DistroFamily.LinuxInstaller => $"  ({p.DisplayName} - Linux installer)",
        DistroFamily.RecoveryTool => $"  ({p.DisplayName} - recovery tool)",
        DistroFamily.MemoryTester => $"  ({p.DisplayName} - memory tester)",
        _ => $"  ({p.DisplayName})",
    };

    private static string EncodePath(string innerPath)
    {
        // DiscUtils stores ISO paths with '\' separators; HTTP URLs need '/'.
        var normalized = innerPath.Replace('\\', '/').TrimStart('/');
        var parts = normalized.Split('/');
        for (var i = 0; i < parts.Length; i++)
        {
            parts[i] = Uri.EscapeDataString(parts[i]);
        }
        return string.Join('/', parts);
    }

    private static string FormatSize(long bytes)
    {
        const double Kb = 1024d;
        const double Mb = Kb * 1024d;
        const double Gb = Mb * 1024d;

        return bytes switch
        {
            < (long)Kb => $"{bytes} B",
            < (long)Mb => $"{bytes / Kb:F0} KB",
            < (long)Gb => $"{bytes / Mb:F0} MB",
            _ => $"{bytes / Gb:F2} GB",
        };
    }

    /// <summary>
    /// Strip characters that would prematurely end an iPXE `echo` line or
    /// confuse the menu parser.
    /// </summary>
    private static string Sanitize(string text) => text
        .Replace("\r", " ", StringComparison.Ordinal)
        .Replace("\n", " ", StringComparison.Ordinal);
}
