using System;
using System.Text;
using Everboot.Configuration;
using Microsoft.Extensions.Options;

namespace Everboot.Services;

/// <summary>
/// Renders the iPXE menu script clients hit at /boot.ipxe. One entry per
/// image in the catalog; per-entry boot logic switches between wimboot,
/// sanboot, and memdisk depending on what the inspector found inside.
/// </summary>
internal sealed class BootConfigGenerator
{
    private readonly BootCatalog _catalog;
    private readonly EverbootOptions _options;

    public BootConfigGenerator(BootCatalog catalog, IOptions<EverbootOptions> options)
    {
        _catalog = catalog;
        _options = options.Value;
    }

    public string GenerateIpxeMenu(string serverAuthority)
    {
        var entries = _catalog.Entries;
        var sb = new StringBuilder(4096);

        sb.AppendLine("#!ipxe");
        sb.AppendLine("# Generated by Everboot");
        sb.AppendLine();
        sb.AppendLine(":start");
        sb.AppendLine($"menu {_options.Menu.Title}");
        sb.AppendLine("item --gap -- ----------- Boot images -----------");

        if (entries.Count == 0)
        {
            sb.AppendLine("item --gap -- (no images found - drop *.iso or *.img into data/isos/)");
        }
        else
        {
            foreach (var entry in entries)
            {
                sb.AppendLine($"item {entry.Slug} {entry.DisplayName}  [{FormatSize(entry.SizeBytes)}]{LabelTag(entry)}");
                if (_options.Menu.IncludeSanbootFallback && HasDirectBoot(entry))
                {
                    sb.AppendLine($"item {entry.Slug}-sanboot {entry.DisplayName}  (sanboot fallback - if direct boot is stale)");
                }
            }
        }

        sb.AppendLine("item --gap -- ------------ Tools -----------------");
        sb.AppendLine("item shell  iPXE shell");
        sb.AppendLine("item reboot Reboot");
        sb.AppendLine("item exit   Exit iPXE (continue local boot)");

        var defaultItem = entries.Count > 0 ? entries[0].Slug : "exit";
        var timeoutMs = Math.Max(0, _options.Menu.TimeoutSeconds) * 1000;
        sb.AppendLine($"choose --default {defaultItem} --timeout {timeoutMs} target && goto ${{target}} || goto cancel");
        sb.AppendLine();

        sb.AppendLine(":cancel");
        sb.AppendLine("echo Menu cancelled, exiting iPXE.");
        sb.AppendLine("exit");
        sb.AppendLine();

        sb.AppendLine(":shell");
        sb.AppendLine("echo Type 'exit' to return to the menu.");
        sb.AppendLine("shell");
        sb.AppendLine("goto start");
        sb.AppendLine();

        sb.AppendLine(":reboot");
        sb.AppendLine("reboot");
        sb.AppendLine();

        sb.AppendLine(":exit");
        sb.AppendLine("exit");
        sb.AppendLine();

        foreach (var entry in entries)
        {
            sb.AppendLine($":{entry.Slug}");
            sb.AppendLine($"echo Booting {entry.DisplayName} ...");

            if (entry.Metadata.IsModernWindows && entry.Metadata.WindowsFiles is { } wf)
            {
                EmitWindowsChain(sb, serverAuthority, entry.Slug, wf);
            }
            else if (entry.Metadata.WindowsEra == WindowsBootEra.NinexClass)
            {
                EmitWin9xNotice(sb);
            }
            else if (entry.Metadata.Profile?.Family == DistroFamily.NotForPxe)
            {
                EmitNotForPxeNotice(sb, entry.Metadata.Profile);
            }
            else if (HasDirectBoot(entry))
            {
                EmitDirectBootWithFallback(sb, serverAuthority, entry);
            }
            else if (entry.IsLikelyFloppy)
            {
                EmitMemdiskChain(sb, serverAuthority, entry);
            }
            else
            {
                if (entry.Metadata.WindowsEra == WindowsBootEra.XpClass)
                {
                    sb.AppendLine("echo NOTE: Windows XP-class PXE boot via sanboot is unreliable. If it hangs, power-cycle.");
                    sb.AppendLine("sleep 3");
                }
                EmitSanbootBody(sb, serverAuthority, entry);
            }

            sb.AppendLine();
        }

        // Always emit the sanboot label for direct-boot entries (used both as
        // explicit menu item when enabled, and as automatic fallback target).
        foreach (var entry in entries)
        {
            if (!HasDirectBoot(entry))
            {
                continue;
            }
            sb.AppendLine($":{entry.Slug}-sanboot");
            sb.AppendLine($"echo Booting {entry.DisplayName} via sanboot ...");
            EmitSanbootBody(sb, serverAuthority, entry);
            sb.AppendLine();
        }

        sb.AppendLine(":bootfail");
        sb.AppendLine("echo Boot failed. Returning to menu in 5s.");
        sb.AppendLine("sleep 5");
        sb.AppendLine("goto start");

        return sb.ToString();
    }

    private static void EmitWindowsChain(StringBuilder sb, string authority, string slug, WindowsBootFiles wf)
    {
        // Both chains available -> branch on iPXE's ${platform} so BIOS and UEFI
        // clients each pick the loader actually shipped on the ISO for them.
        if (wf.HasBiosChain && wf.HasEfiChain)
        {
            sb.AppendLine($"iseq $" + "{platform} efi && goto " + $"{slug}-efi || goto {slug}-bios");
            sb.AppendLine();
            sb.AppendLine($":{slug}-bios");
            EmitBiosChain(sb, authority, slug, wf);
            sb.AppendLine();
            sb.AppendLine($":{slug}-efi");
            EmitEfiChain(sb, authority, slug, wf);
            return;
        }

        if (wf.HasBiosChain)
        {
            EmitBiosChain(sb, authority, slug, wf);
        }
        else
        {
            EmitEfiChain(sb, authority, slug, wf);
        }
    }

    private static void EmitBiosChain(StringBuilder sb, string authority, string slug, WindowsBootFiles wf)
    {
        sb.AppendLine($"set base http://{authority}/iso/{slug}");
        sb.AppendLine($"set wimboot-url http://{authority}/files/wimboot");
        sb.AppendLine("kernel ${wimboot-url} || goto bootfail");
        sb.AppendLine($"initrd --name bootmgr     ${{base}}/{EncodePath(wf.Bootmgr!)}     bootmgr");
        sb.AppendLine($"initrd --name BCD         ${{base}}/{EncodePath(wf.Bcd!)}         BCD");
        sb.AppendLine($"initrd --name boot.sdi    ${{base}}/{EncodePath(wf.BootSdi!)}    boot.sdi");
        sb.AppendLine($"initrd --name boot.wim    ${{base}}/{EncodePath(wf.BootWim)}    boot.wim");
        sb.AppendLine("boot || goto bootfail");
    }

    private static void EmitEfiChain(StringBuilder sb, string authority, string slug, WindowsBootFiles wf)
    {
        sb.AppendLine($"set base http://{authority}/iso/{slug}");
        sb.AppendLine($"set wimboot-url http://{authority}/files/wimboot");
        sb.AppendLine("kernel ${wimboot-url} || goto bootfail");
        sb.AppendLine($"initrd --name BCD         ${{base}}/{EncodePath(wf.BcdEfi!)}     BCD");
        if (wf.BootmgrEfi is not null)
        {
            sb.AppendLine($"initrd --name bootmgfw.efi ${{base}}/{EncodePath(wf.BootmgrEfi)} bootmgfw.efi");
        }
        sb.AppendLine($"initrd --name boot.wim    ${{base}}/{EncodePath(wf.BootWim)}    boot.wim");
        sb.AppendLine("boot || goto bootfail");
    }

    private static bool HasDirectBoot(IsoEntry entry) =>
        entry.Metadata.Profile?.DirectBoot is not null && !entry.Metadata.IsModernWindows;

    private static string LabelTag(IsoEntry entry)
    {
        // Caveats from a profile win first - that's where DBAN/Ventoy live.
        if (entry.Metadata.Profile?.Caveat is { } caveat)
        {
            return $"  ({entry.Metadata.Profile.DisplayName} - {caveat})";
        }

        return entry.Metadata.WindowsEra switch
        {
            WindowsBootEra.Modern => entry.Metadata.Profile is { } mp
                ? $"  ({mp.DisplayName} - Windows)"
                : "  (Windows)",
            WindowsBootEra.XpClass => "  (Windows XP-era - PXE may fail)",
            WindowsBootEra.NinexClass => "  (Windows 9x - not PXE-bootable)",
            _ => entry.IsLikelyFloppy
                ? "  (floppy via memdisk)"
                : entry.Metadata.Profile is { } p
                    ? FamilyLabel(p)
                    : string.Empty,
        };
    }

    private static string FamilyLabel(DistroProfile p) => p.Family switch
    {
        DistroFamily.LinuxLive => $"  ({p.DisplayName} - Linux Live)",
        DistroFamily.LinuxInstaller => $"  ({p.DisplayName} - Linux installer)",
        DistroFamily.RecoveryTool => $"  ({p.DisplayName} - recovery tool)",
        DistroFamily.MemoryTester => $"  ({p.DisplayName} - memory tester)",
        _ => $"  ({p.DisplayName})",
    };

    private static void EmitWin9xNotice(StringBuilder sb)
    {
        sb.AppendLine("echo Windows 9x install media cannot boot directly via PXE.");
        sb.AppendLine("echo To install: PXE-boot FreeDOS via 'kernel memdisk' + a DOS floppy image,");
        sb.AppendLine("echo then run setup.exe from a mounted network share.");
        sb.AppendLine("echo Returning to menu in 8 seconds.");
        sb.AppendLine("sleep 8");
        sb.AppendLine("goto start");
    }

    private static void EmitMemdiskChain(StringBuilder sb, string authority, IsoEntry entry)
    {
        sb.AppendLine($"kernel http://{authority}/files/memdisk || goto bootfail");
        sb.AppendLine($"initrd http://{authority}/isos/{Uri.EscapeDataString(entry.FileName)}");
        sb.AppendLine("boot || goto bootfail");
    }

    private static void EmitNotForPxeNotice(StringBuilder sb, DistroProfile profile)
    {
        sb.AppendLine($"echo {profile.DisplayName} is not a PXE boot target.");
        if (profile.Caveat is not null)
        {
            sb.AppendLine($"echo {profile.Caveat}");
        }
        sb.AppendLine("echo Returning to menu in 5 seconds.");
        sb.AppendLine("sleep 5");
        sb.AppendLine("goto start");
    }

    private static void EmitDirectBootWithFallback(StringBuilder sb, string authority, IsoEntry entry)
    {
        // Pre-condition: HasDirectBoot returned true, so Profile + DirectBoot are non-null.
        var profile = entry.Metadata.Profile!;
        var direct = profile.DirectBoot!;

        var args = direct.KernelArgs
            .Replace("{server}", authority, StringComparison.Ordinal)
            .Replace("{slug}", entry.Slug, StringComparison.Ordinal)
            .Replace("{file}", Uri.EscapeDataString(entry.FileName), StringComparison.Ordinal);

        sb.AppendLine($"echo Direct kernel boot via {profile.DisplayName} profile (will fall back to sanboot on failure)...");
        sb.AppendLine($"kernel http://{authority}/iso/{entry.Slug}/{EncodePath(direct.KernelPath)} {args} || goto {entry.Slug}-sanboot");
        sb.AppendLine($"initrd http://{authority}/iso/{entry.Slug}/{EncodePath(direct.InitrdPath)} || goto {entry.Slug}-sanboot");
        sb.AppendLine($"boot || goto {entry.Slug}-sanboot");
    }

    private void EmitSanbootBody(StringBuilder sb, string authority, IsoEntry entry)
    {
        if (_options.Iscsi.Enabled && _options.Iscsi.UseForSanboot)
        {
            var host = authority.Split(':')[0]; // strip port - iSCSI uses 3260
            var iqn = $"{_options.Iscsi.IqnBase}:iso-{entry.Slug}";
            sb.AppendLine($"set iscsi-target iscsi:{host}::::{iqn}");
            sb.AppendLine("sanboot --no-describe ${iscsi-target} || goto bootfail");
        }
        else
        {
            sb.AppendLine($"set iso-url http://{authority}/isos/{Uri.EscapeDataString(entry.FileName)}");
            sb.AppendLine("sanboot --no-describe ${iso-url} || goto bootfail");
        }
    }

    private static string EncodePath(string innerPath)
    {
        // DiscUtils stores ISO paths with '\' separators; HTTP URLs need '/'.
        var normalized = innerPath.Replace('\\', '/').TrimStart('/');
        var parts = normalized.Split('/');
        for (var i = 0; i < parts.Length; i++)
        {
            parts[i] = Uri.EscapeDataString(parts[i]);
        }
        return string.Join('/', parts);
    }

    private static string FormatSize(long bytes)
    {
        const double Kb = 1024d;
        const double Mb = Kb * 1024d;
        const double Gb = Mb * 1024d;

        return bytes switch
        {
            < (long)Kb => $"{bytes} B",
            < (long)Mb => $"{bytes / Kb:F0} KB",
            < (long)Gb => $"{bytes / Mb:F0} MB",
            _ => $"{bytes / Gb:F2} GB",
        };
    }
}
